add scss sourcempas to webpack + app weight analyzer
opstalent/React-Redux-Startekit pull request #4
Opened 2017-10-18 12:05 UTC by Druzzdil

2017-10-19 09:54 UTC, patgrudniewski requested changes

2017-10-19 09:54 UTC, patgrudniewski commented on webpack.config.js
> +    new BundleAnalyzerPlugin(),
add it to dev's webpack

2017-10-19 11:47 UTC, Druzzdil commented on webpack.config.js
> +    new BundleAnalyzerPlugin(),
no problem

2017-10-19 12:07 UTC, bartij approved these changes

2017-10-23 08:06 UTC, patgrudniewski requested changes

2017-10-23 08:06 UTC, patgrudniewski commented on webpack.config.js
> +module.exports = require('./webpack.config.js');
why it is requiring itself?

2017-10-23 08:06 UTC, patgrudniewski commented on webpack.dev.config.js
> +const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
disable autostart of it

2017-10-23 08:06 UTC, patgrudniewski commented on webpack.config.js
> +module.exports.plugins.push(new webpack.HotModuleReplacementPlugin());
why non-dev webpack config contains `HotModuleReplacementPlugin`?

2017-10-23 08:06 UTC, patgrudniewski commented on webpack.config.js
> -const path = require('path');
`npm run build` is not working

2017-10-23 08:06 UTC, patgrudniewski commented on webpack.dev.config.js
> +const app_root = './src';
add space between `includes` and `variables`

2017-10-23 08:06 UTC, patgrudniewski commented on webpack.config.js
> -const path = require('path');
`TypeError: Cannot set property 'hot' of undefined`

2017-10-23 09:31 UTC, Druzzdil commented on webpack.dev.config.js
> +const app_root = './src';
it's not ok like it is ?

2017-10-23 10:57 UTC, auamarto commented on webpack.dev.config.js
> +const app_root = './src';
add empty line before app_root other lines are imports it's just visual thing but yes its not ok for us ;]

2017-10-24 08:23 UTC, patgrudniewski requested changes

2017-10-24 08:23 UTC, patgrudniewski commented on package.json
> -    "whatwg-fetch": "^2.0.1"
remove it from `README.md`

2017-10-24 08:23 UTC, patgrudniewski commented on package.json
> +    "webpack-bundle-analyzer": "^2.9.0",
add it to `README.md`

2017-10-24 08:23 UTC, patgrudniewski commented on webpack.config.js
> +module.exports = require('./webpack.dev.config.js');
why base `webpack` is loading `dev` one?

2017-10-24 08:23 UTC, patgrudniewski commented on webpack.config.js
> +module.exports.devServer.hot = true;
is this used on prod?

2017-10-24 08:23 UTC, patgrudniewski commented on webpack.dev.config.js
> +const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
require it [here](https://github.com/opstalent/React-Redux-Startekit/pull/4/files#diff-361932ce6b04b8880716e7995633922aR3)

2017-10-30 09:58 UTC, auamarto reviewed
after README.md edit it's ok for me

2017-10-31 08:22 UTC, auamarto approved these changes

2017-10-31 08:22 UTC, merged

2017-11-06 06:28 UTC, patgrudniewski commented on webpack.config.js
> +    new BundleAnalyzerPlugin({
is it needed for prod env?